### ISSUE TITLE
Credentials visible on the staging code

### ISSUE THREAD

**Issue by palaniappan47** [tnemis/staging-server#13]
Kind attention to Mr.magesh

Kindly remove the following from settings.py of live-server code and staging-server codes on git hub,

1. secret key,
2. database host ip,
3. data base user name,
4. database password,
5. data base port number,
6. Proxy ip mentioned in line number 11 & 12 of settings.py file,

Since the code is visible and down loadable publicly to anyone over the inter-net these informations will be a serious threat to applications hosted and database.

Team members are requested to follow the necessary steps to avoid revealing the credentials

**Comment by emisteam** [comment]
code updated. Team members ensure that while pushing code to repo , change these things.
